#!/bin/sh

# ---------------------------------------------
# cluster_and_generate
#   helper script to run various steps to generate visualizations
#   - runs fcluster on all data
#   - generates figures based on clustered data
#   - converts image directories to .mp4 files
# ---------------------------------------------

K_VALUES="5 6 7 8 9 10"

CONVERTED_DATA_DIR="../Data/converted"
CLUSTERED_DATA_DIR="../Data/fclustered"
VISUALIZATION_DIR="../Visualization"


for k in $K_VALUES; do
    echo "k=$k"
    echo "-----"

    # Run the clustering algorithm on converted data
    python fcluster.py -i "$CONVERTED_DATA_DIR" -k $k -o "k=$k"

    # Generate figures (map/line) based on the clustered data
    python generate_map.py -i "$CLUSTERED_DATA_DIR/k=$k" -o "$VISUALIZATION_DIR/map/k_$k" -k $k
    python generate_line_graph.py -i "$CLUSTERED_DATA_DIR/k=$k" -o "$VISUALIZATION_DIR/line/k_$k" -k $k

    # Generate mp4 files from the figures
    ./convert_image_sequences "$VISUALIZATION_DIR/map/k_$k"
    ./convert_image_sequences "$VISUALIZATION_DIR/line/k_$k"

    echo
done
