#!/bin/sh

BASE_DIR=$(pwd)
VARIABLES="
    two_metre_temperature
    sea_surface_temperature
    mean_sea_level_pressure
    total_cloud_cover"

OUTPUT_DIR="${1:-output/img}"   # directory containing the images
FRAMERATE="${2:-30}"            # desired output framerate
EXT_OUT="mp4"                   # extension of the file ffmpeg should output
OVERWRITE=false                 # should ffmpeg blindly overwrite files?

echo "Creating $FRAMERATE FPS $EXT_OUT image sequences in $OUTPUT_DIR"

for variable in $VARIABLES; do
    cd "$OUTPUT_DIR/$variable"
    filename="_${variable}_$FRAMERATE.$EXT_OUT" 
    echo "Creating $filename"
    ffmpeg ${OVERWRITE:+-y} -hide_banner -loglevel panic -framerate $FRAMERATE -i %d.png "$filename"

    cd "$BASE_DIR"
done
